inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/migrate/**
    - db/schema.rb
    - vendor/**/*

Rails:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/initializers/dor_config.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/services/cocina/etd_description_builder.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/services/cocina/etd_description_builder.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Max: 8
  Enabled: false

RSpec/MultipleExpectations:
  Max: 19

RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**'
