# SSL
ssl:
  cert_file: "/etc/pki/tls/certs/<%= (`echo $HOSTNAME`).strip.gsub('.stanford.edu', '') %>-dor-prod.crt"
  key_file: "/etc/pki/tls/private/<%= (`echo $HOSTNAME`).strip.gsub('.stanford.edu', '') %>-dor-prod.key"
  key_pass: 'password'

content:
  base_dir: '/dor/workspace'

# Stacks
stacks:
  document_cache_host: 'purl-test.stanford.edu'
  local_workspace_root: '/dor/workspace'
  local_stacks_root: '/stacks'
  local_document_cache_root: '/purl/document_cache'

# Suri
suri:
  mint_ids: true
  id_namespace: 'druid'
  url: 'https://suri.example.com'
  user: 'user'
  pass: 'pass'

# Workflow
workflow:
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'

# URLs
fedora_url: 'https://user:password@fedora.example.com:1000/fedora'
solr:
  url: 'https://solr.example.com/solr/collection'

workflow_url: 'https://workflow.example.com/workflow'
sdr_url: 'http://sdr-services.example.com/sdr'
purl_services_url: ~

cleanup:
  local_workspace_root: '/dor/workspace'
  local_assembly_root: '/dor/assembly'
  local_export_home: '/dor/export'

dor:
  service_user: 'user'
  service_password: 'password'
  hmac_secret: 'my$ecretK3y'

release:
  symphony_path: './'
  write_marc_script: 'bin/write_marc_record_test'
  purl_base_url: 'http://purl.stanford.edu'

goobi:
  url: 'http://goobi-env.stanford.edu:9292'
  dpg_workflow_name: 'goobiWF'
  default_goobi_workflow_name: 'Example_Workflow'
  max_tries: 3
  max_sleep_seconds: 20
  base_sleep_seconds: 2

catalog:
  barcode_search_url: "https://searchworks.stanford.edu/barcode/%{barcode}"
  symphony:
    json_url: "https://sirsi.example.com/symws/v1/catalog/bib/key/%{catkey}?includeFields=bib"
    headers:
      SD-ORIGINATING-APP-ID: DOR-SERVICES-APP
      SD-PREFERRED-ROLE: GUEST
